### ISSUE TITLE
worker sent an error! undefined:undefined: undefined

### ISSUE THREAD

**Issue by NeroBurner** [gzuidhof/coi-serviceworker#4]
I'm trying to work around the gh-pages COOP/COEP limitation using your handy library. Unfortunately I have no luck doing so

The site/app in question is deployed at https://infinitimeorg.github.io/InfiniSim/infinisim.html

The workflow filling the file can be found at https://github.com/InfiniTimeOrg/InfiniSim/blob/emscripten_build_ci/.github/workflows/emsdk.yml

The side reloads as expected and a `infinisim.worker.js` is created/registered

Unfortunately there is s 404 Error (screenshot of Chromium console)

![image](https://user-images.githubusercontent.com/9076163/161152390-e77be5b9-35bd-4702-a9af-f839c0c77aaf.png)

InfiniSim is a simulator for Infinitime written in C++ compiling with emscripten to wasm. Because of the pthread and SDL2 dependency COOP/COEP is needed for the `SharedArrayBuffer` feature.

I'm injecting the `coi-serviceworker.js` script directly after the `</title>`  tag into the generated `infinisim.html` using a little `sed` magic
```sh
sed -i -e 's#</title>#</title><script src="./coi-serviceworker.js"></script>#' build_em/infinisim.html
```

Locally running the file with `emrun infinisim.html` works with Chromium

I'm out of ideas and hope you can help me

**Comment by tamo** [comment]
I don't think it has anything to do with coi-serviceworker.
I cannot GET https://infinitimeorg.github.io/InfiniSim/infinisim.worker.js either with or without COI.  I'm sure you know what 404 means. That's it.
Your infinisim.js does `locateFile("infinisim.worker.js")` but you haven't published infinisim.worker.js there, have you?
You were able to `emrun` locally because you had infinisim.worker.js locally, but maybe the remote server doesn't have it.

**Comment by NeroBurner** [comment]
you were right! Sorry about the noise and a big THANK YOU! :bow:
